modules:
  prereg:
    enabled: true
    image:
      repository: mosipid/apitest-prereg
      tag: 1.3.0
      pullPolicy: Always
  masterdata:
    enabled: true
    image:
      repository: mosipid/apitest-masterdata
      tag: 1.3.0
      pullPolicy: Always
  idrepo:
    enabled: true
    image:
      repository: mosipid/apitest-idrepo
      tag: 1.3.0
      pullPolicy: Always
  partner:
    enabled: true
    image:
      repository: mosipid/apitest-pms
      tag: 1.2.2.2
      pullPolicy: Always
  resident:
    enabled: true
    image:
      repository: mosipid/apitest-resident
      tag: 1.3.0
      pullPolicy: Always
  auth:
    enabled: true
    image:
      repository: mosipid/apitest-auth
      tag: 1.3.0
      pullPolicy: Always
