# Refrain from fixing docker tags. Instead use the appropriate chart version, while helm install
# Latest Helm chart of Bitnami uses Keycloak 18+ 

# Refrain from fixing docker tags. Instead use the appropriate chart version, while helm install
# Latest Helm chart of Bitnami uses Keycloak 18+ 

## PostgreSQL chart configuration
## ref: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml
## @param postgresql.enabled Switch to enable or disable the PostgreSQL helm chart
## @param postgresql.auth.username Name for a custom user to create
## @param postgresql.auth.password Password for the custom user to create
## @param postgresql.auth.database Name for a custom database to create
## @param postgresql.auth.existingSecret Name of existing secret to use for PostgreSQL credentials
## @param postgresql.architecture PostgreSQL architecture (`standalone` or `replication`)
##
postgresql:
  enabled: true
  auth:
    username: bn_keycloak
    password: ""
    database: bitnami_keycloak
    existingSecret: ""
  architecture: standalone
  ## Replication config (uncomment to enable PostgreSQL HA)
  # architecture: replication
  # readReplicas:
  #   replicaCount: 1
  #   resources:
  #     requests:
  #       cpu: 250m
  #       memory: 512Mi
  #     limits:
  #       cpu: 1000m
  #       memory: 1Gi
  #   persistence:
  #     enabled: true
  #     storageClass: ""
  #     accessModes:
  #       - ReadWriteOnce
  #     size: 8Gi
  # image:
  #   registry: docker.io
  #   repository: mosipid/postgresql
  #   tag: "14.2.0-debian-10-r70"
  primary:
    resources:
      requests:
        cpu: 512m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 8Gi
    extendedConfiguration: |
      max_connections = 200
      shared_buffers = 512MB
      work_mem = 4MB
      maintenance_work_mem = 128MB
      effective_cache_size = 1536MB
## External PostgreSQL configuration
## All of these values are only used when postgresql.enabled is set to false
## @param externalDatabase.host Database host
## @param externalDatabase.port Database port number
## @param externalDatabase.user Non-root username for Keycloak
## @param externalDatabase.password Password for the non-root username for Keycloak
## @param externalDatabase.database Keycloak database name
## @param externalDatabase.existingSecret Name of an existing secret resource containing the database credentials
## @param externalDatabase.existingSecretPasswordKey Name of an existing secret key containing the database credentials
##
# externalDatabase:
#   host: ""
#   port: 5432
#   user: bn_keycloak
#   database: bitnami_keycloak
#   password: ""
#   existingSecret: ""
#   existingSecretPasswordKey: ""

service:
  type: ClusterIP

auth:
  adminUser: admin

extraEnvVars:
  - name: KEYCLOAK_EXTRA_ARGS
    value: "-Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.profile.feature.token_exchange=enabled -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled"
    #value: "-Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.import=/config/realm-mosip.json"

## Disable ingress as we use Istio
ingress:
  enabled: false
  hostname:
  annotations:
    ingress.kubernetes.io/class: nginx

proxyAddressForwarding: true

replicaCount: 1

# Enable if replicaCount > 1
serviceDiscovery:
  enabled: true

resources:
  limits: {}
  #   cpu: 250m
  #   memory: 1Gi
  requests:
    cpu: 200m
    memory: 1000Mi

rbac:
  create: true
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - list
