#!/bin/python3

import sys
import argparse
from machine_api import *
import csv
import json
import config as conf
sys.path.insert(0, '../')
from utils import *

def add_machine_type(csv_file):
    session = MosipSession(conf.server, conf.superadmin_user, conf.superadmin_pwd)
    reader = csv.DictReader(open(csv_file, 'rt')) 
    for row in reader:
        myprint('Adding machine type %s' % row['name'])
        r = session.add_machine_type(row['code'], row['name'], row['description'], row['language'])
        r = response_to_json(r)
        myprint(r)
        if r['errors'] is not None:
            if r['errors'][0]['errorCode'] == 'KER-MSD-994' or \
               r['errors'][0]['errorCode'] == 'KER-MSD-061':
                myprint('Updating machine type for "%s"' % row['name'])
                r = session.update_machine_type(row['code'], row['name'], row['description'], row['language'])
                r = response_to_json(r)
                myprint(r)

#def add_machine_spec(self, machine_id, name, type_code,  brand, model, description, language, min_driver_ver)
def add_machine_spec(csv_file):
    session = MosipSession(conf.server, conf.superadmin_user, conf.superadmin_pwd)
    reader = csv.DictReader(open(csv_file, 'rt')) 
    spec_id = 'any' # Just a placeholder
    for row in reader:
            myprint('Adding machine spec (%s,%s)' % (row['name'], row['language']))
            r = session.add_machine_spec(spec_id, row['name'], row['type_code'], row['brand'], row['model'],
                                         row['description'], row['language'], row['min_driver_ver'])
            r = response_to_json(r)
            myprint(r)
            if r['errors'] is not None:
                myprint('ABORTING')
                break
            
            if row['language'] == conf.primary_lang:
                spec_id = r['response']['id']  # Spec id is generated by mosip, so use that in the next step
            else:
                spec_id = 'any'
                
 
def args_parse(): 
   parser = argparse.ArgumentParser()
   parser.add_argument('action', help='type|spec|all')
   args = parser.parse_args()
   return args

def main():

    init_logger('./out.log')
    args = args_parse()

    if args.action == 'type' or args.action == 'all':
        add_machine_type(conf.csv_machine_type)
    if args.action == 'spec' or args.action == 'all':
        add_machine_spec(conf.csv_machine_spec)

if __name__=="__main__":
    main()
