#!/bin/python3

import sys
import argparse
from api import *
import csv
import json
import config as conf
sys.path.insert(0, '../')
from utils import *

def add_machine_type(files):
    session = MosipSession(conf.server, conf.superadmin_user, conf.superadmin_pwd)
    for f in files:
        j  = json.load(open(f, 'rt'))
        for i,l in enumerate(j['languages']):
            myprint('Adding machine type (%s,%s)' % (j['code'], j['languages'][i]))
            r = session.add_machine_type(j['code'], j['name'][i], j['description'][i], j['languages'][i])
            r = response_to_json(r)
            if r['errors'] is None:
                 continue 
            else:
                if r['errors'][0]['errorCode'] == 'KER-MSD-994' or \
                   r['errors'][0]['errorCode'] == 'KER-MSD-061':
                    myprint('Updating machine type (%s,%s)' % (j['code'], j['languages'][i]))
                    r = session.update_machine_type(j['code'], j['name'][i], j['description'][i], j['languages'][i])
                    r = response_to_json(r)
                    if r['errors'] is None:
                        continue
                myprint(r)
           

def add_machine_spec(files):
    session = MosipSession(conf.server, conf.superadmin_user, conf.superadmin_pwd)
    spec_id = 'any' # Just a placeholder
    for f in files:
        j  = json.load(open(f, 'rt'))
        for i,language in enumerate(j['languages']):
            myprint('Adding machine spec (%s,%s)' % (j['name'][i], language))
            r = session.add_machine_spec(spec_id, j['name'][i], j['type_code'], j['brand'][i], j['model'][i],
                                         j['description'][i], language, j['min_driver_ver'])
            r = response_to_json(r)
            if r['errors'] is not None:
                myprint('ABORTING')
                break
            
            if language == conf.primary_lang:
                spec_id = r['response']['id']  # Spec id is generated by mosip, so use that in the next step
            else:
                spec_id = 'any'
                
def get_machine_spec_id(spec_name, language):
    session = MosipSession(conf.server, conf.superadmin_user, conf.superadmin_pwd)
    r = session.get_machine_specs()
    r = response_to_json(r)
    spec_id = None
    if r['errors'] is None:
        for spec in r['response']['data']: 
            if spec['name'] == spec_name and spec['langCode'] == language:
                spec_id = spec['id']  
                break
    return spec_id

def add_machine(files):
    session = MosipSession(conf.server, conf.superadmin_user, conf.superadmin_pwd)
    for f in files:
        j  = json.load(open(f, 'rt'))
        machine_id = ''
        for i,language in enumerate(j['languages']):
            myprint('Adding machine (%s,%s)' % (j['name'][i], language))
            spec_id = get_machine_spec_id(j['spec_name'][i], language)
            if spec_id is None:
                myprint('ABORTING: spec id for (%s,%s) not found' % (j['name'][i], language))
                break
            pub_key = open(j['pub_key_path'], 'rt').read().strip()
            sign_pub_key = open(j['sign_pub_key_path'], 'rt').read().strip()
            r = session.add_machine(machine_id, j['name'][i], spec_id, pub_key, j['reg_center_id'], 
                                    j['serial_num'], sign_pub_key, j['validity'], j['zone_id'], language)
            r = response_to_json(r)
            myprint(r)
            if language == conf.primary_lang:
                machine_id = r['response']['id']  # Spec id is generated by mosip, so use that in the next step
            else:
                machine_id = ''

def args_parse(): 
   parser = argparse.ArgumentParser()
   parser.add_argument('action', help='type|spec|machine')
   parser.add_argument('path', help='directory or file containing input data json')
   parser.add_argument('--server', type=str, help='Full url to point to the server.  Setting this overrides server specified in config.py')
   parser.add_argument('--disable_ssl_verify', help='Disable ssl cert verification while connecting to server', action='store_true')
   args = parser.parse_args()
   return args, parser

def main():

    args, parser =  args_parse() 

    if args.server:
        conf.server = args.server   # Overide

    if args.disable_ssl_verify:
        conf.ssl_verify = False

    files = path_to_files(args.path)

    init_logger('full', 'a', './out.log', level=logging.INFO)  # Append mode
    init_logger('last', 'w', './last.log', level=logging.INFO, stdout=False)  # Just record log of last run

    if args.action == 'type':
        add_machine_type(files)
    if args.action == 'spec':
        add_machine_spec(files)
    if args.action == 'machine':
        add_machine(files)

if __name__=="__main__":
    main()
