
## Increase in production
replicaCount: 1
## We are using official clamav docker instead of mailu/clamav that was present originally
image:
  repository: mosipid/clamav
  tag: 1.3.0_base
 # pullPolicy: Always
