{
 "title": "Resident Service Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API Response Time (s):95 percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "api_response_time_seconds{quantile=\"0.95\",service=\"resident\"} > 0",
     "legendFormat": "{{method}}{{uri}};status:{{status}};execption:{{exception}}"
    }
   ]
  },
  {
   "title": "Max API Response Time (s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "api_response_time_seconds_max > 0",
     "legendFormat": "{{method}}{{uri}};status:{{status}};execption:{{exception}}"
    }
   ]
  },
  {
   "title": "API Call count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "api_response_time_seconds_count > 0",
     "legendFormat": "{{method}}{{uri}};status:{{status}};execption:{{exception}}"
    }
   ]
  },
  {
   "title": "DB Query Response Time:95 Percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "db_query_response_time_seconds{quantile=\"0.95\"} > 0",
     "legendFormat": "{{queryMethod}}"
    }
   ]
  },
  {
   "title": "Max DB Query Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "db_query_response_time_seconds_max > 0",
     "legendFormat": "{{queryMethod}}"
    }
   ]
  },
  {
   "title": "DB Query Response Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "db_query_response_time_seconds_count > 0",
     "legendFormat": "{{queryMethod}}"
    }
   ]
  },
  {
   "title": "Server side Rest API Calls response time:95 Percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rest_client_response_time_seconds{service=\"resident\", quantile=\"0.95\"} > 0",
     "legendFormat": "{{httpMethod}}:{{url}};status:{{httpStatus}};error={{error}}"
    }
   ]
  },
  {
   "title": "Server side Rest API Calls: Max response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rest_client_response_time_seconds_max > 0",
     "legendFormat": "{{httpMethod}}:{{url}};status:{{httpStatus}};error={{error}}"
    }
   ]
  },
  {
   "title": "Server side Rest API Calls Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rest_client_response_time_seconds_count > 0",
     "legendFormat": "{{httpMethod}}:{{url}};status:{{httpStatus}};error={{error}}"
    }
   ]
  }
 ]
}