import subprocess
import os
import logging
import time
import sys
from common import *
from config import *
import base64

logger = logging.getLogger(__name__)

def create_context_entry(partition_name):
    '''
    Context template is generated by stringfying this:
    dn: c=<country_name>
    c: <country_name> 
    objectclass: domain
    objectclass: top
    dc: <country_name> 
    '''
    template = 'dn: c=%s\nc: %s\nobjectclass: domain\nobjectclass: top\ndc: %s'
    pn = partition_name
    ce = template % (pn, pn, pn)
    b = base64.b64encode(bytes(ce, 'utf-8'))  # bytes type
    return b.decode()  # Convert bytes to str 

def restart_apacheds():
    command('sudo /opt/apacheds-2.0.0.AM25/bin/apacheds restart default')
    time.sleep(10.0)  # Need to wait for server to start. TODO make this better

def install_apacheds(): 
    command('wget http://mirrors.estointernet.in/apache//directory/apacheds/dist/2.0.0.AM25/apacheds-2.0.0.AM25-64bit.bin')
    command('chmod 755 apacheds-2.0.0.AM25-64bit.bin')
    command('sudo useradd -M apacheds') 
    command('sudo ./apacheds-2.0.0.AM25-64bit.bin')
    command('sudo yum -y install openldap-clients')
    command('sudo yum -y install openldap-devel')
    restart_apacheds()

def load_ldap(partition_name):
    create_partition(partition_name) 
    load_data()
   
def load_data():
    logger.info('Loading with sample data')
    command('ldapmodify -h localhost -p 10389 -D "uid=admin,ou=system" -w "secret" -a -f ./resources/ldap/mosip-schema-extn.ldif')
    command('ldapmodify -h localhost -p 10389 -D "uid=admin,ou=system" -w "secret" -a -f ./resources/ldap/mosip-entries.ldif')

    restart_apacheds()

def create_partition(partition_name): 
    logger.info('Creating partition for %s' % partition_name)
    s = open('./resources/ldap/partition_template.ldif').read()
    s = s.replace('[partition_name]', partition_name)
    context_entry = create_context_entry(partition_name) 
    s = s.replace('[context_entry]', context_entry)
    ldif = '/tmp/partition.ldif'
    f = open(ldif, 'wt')
    f.write(s) 
    f.close()
    command('ldapmodify -h localhost -p 10389 -D "uid=admin,ou=system" -w "secret" -a -f %s' % ldif)
    restart_apacheds()
